#!/bin/bash

ssh quotiful@s4.sourcepad.com "cd staging && git pull && script/restart"
ssh quotiful@ws0.quotiful.com "cd current && git pull && script/restart"
ssh quotiful@ws1.quotiful.com "cd current && git pull && script/restart"
ssh quotiful@dbs0.quotiful.com "cd current && git pull && script/restart"

curl "http://quotiful.sourcepadstage.com/"
curl "http://ws0.quotiful.com/"
curl "http://ws1.quotiful.com/"
curl "http://dbs0.quotiful.com/"